# Generated by Django 4.1.4 on 2023-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
