# Generated by Django 4.1.4 on 2023-06-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('effective_from', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseprogram',
            constraint=models.UniqueConstraint(fields=('course_id', 'id', 'effective_from'), name='unique_courseProgram'),
        ),
    ]
