# Generated by Django 4.1.4 on 2023-06-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_program_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('course_type', models.CharField(max_length=30)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseProgram',
        ),
        migrations.AddConstraint(
            model_name='courseoffered',
            constraint=models.UniqueConstraint(fields=('course_id', 'program_id', 'year', 'sem'), name='unique_courseOffered'),
        ),
    ]
