# Generated by Django 4.1.4 on 2023-06-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseid', to='core.course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursetype', to='core.courseoffered')),
                ('faculty_sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultysname', to='core.coursefaculty')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programid', to='core.program')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesection', to='core.coursefaculty')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classsem', to='core.courseoffered')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseslot', to='core.slots')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classyear', to='core.courseoffered')),
            ],
        ),
    ]
