# Generated by Django 4.1.4 on 2023-07-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_slots_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseslot', to='core.courseslots'),
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
