# Generated by Django 4.1.4 on 2023-07-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_courseslots_alter_timetable_slot_delete_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseid', to='core.courseoffered'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programid', to='core.courseoffered'),
        ),
    ]
