# Generated by Django 4.1.4 on 2023-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_timetable_course_id_alter_timetable_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseid', to='core.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programid', to='core.program'),
        ),
    ]
