# Generated by Django 4.1.4 on 2023-11-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lecturetimetable_delete_timetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autumn_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('section', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('faculty_sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
        ),
        migrations.AddConstraint(
            model_name='autumn_one',
            constraint=models.UniqueConstraint(fields=('course_id', 'program_id', 'year', 'section'), name='unique_autumn1'),
        ),
    ]
