# Generated by Django 4.1.4 on 2023-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_winter_one_autumn_two_winter_one_unique_winter1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumn_one',
            name='year',
            field=models.CharField(max_length=1),
        ),
    ]
