# Generated by Django 4.1.4 on 2023-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_autumn_one_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumn_two',
            name='year',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='winter_one',
            name='year',
            field=models.CharField(max_length=1),
        ),
    ]
