# Generated by Django 4.1.4 on 2023-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_autumn_two_year_alter_winter_one_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumn_one',
            name='section',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='autumn_one',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='autumn_two',
            name='section',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='autumn_two',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='winter_one',
            name='section',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='winter_one',
            name='year',
            field=models.IntegerField(),
        ),
    ]
