# Generated by Django 4.1.4 on 2023-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_autumn_one_section_alter_autumn_one_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumn_one',
            name='faculty_sname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='autumn_two',
            name='faculty_sname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='winter_one',
            name='faculty_sname',
            field=models.CharField(max_length=30),
        ),
    ]
