# Generated by Django 4.1.4 on 2023-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_acad_year_acad_year_unique_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autumn_one',
        ),
    ]
