# Generated by Django 4.1.4 on 2023-11-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_autumn_one'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winter_one',
        ),
    ]
