# Generated by Django 4.1.4 on 2023-11-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_winter_one'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autumn_two',
        ),
    ]
